FROM amazoncorretto:11-alpine-jdk
MAINTAINER emaaristimuno
COPY target/PortafolioLeidy-0.0.1-SNAPSHOT.jar PortafolioLeidy-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/PortafolioLeidy-0.0.1-SNAPSHOT.jar"]